### ISSUE TITLE
The way forward

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#58]
Now that the JCP module has been finished, you are free to work on the software based on personal conviction. I will also be inviting some other people to collaborate.

I intend to do much planning and most likely a rewrite of the nodejs version we have now.

We have the following options:
- Make a new repo for the rewrite
    - This way we keep the work we have already done separate from the new work
- Use the current repo and replace all the content.
    - Keeps all things in one place, but the Git history will not make much sense. It will basically be two projects that are spliced at some point.

I would like to keep the commits we have now to honour the work the original team has done. I propose we keep the current repo and tag the legacy nodejs code. It will still be released as prothesis v2.0.0

**Comment by RagingGrim** [comment]
Seems like a good idea!

I would also like to invite someone to help out on the project if that's alright.

Do we plan on using nodejs again for the project or will we be porting to C++? At the same time, are we going to use electron or something like Qt or GTK?

**Comment by egeldenhuys** [comment]
You are welcome to invite poeple to help out. I would appreciate it!

I feel this time we need to do research on what language and frameworks to use based on the contraints. I want us to plan and prototype the design before we actually implement anything. I feel the best thing we learned from this version is a uniform method of saving and loading the data.

My problem with HTML is the GUI design takes more time than anything else. But if someone can make a good argument as to why we should use nodejs and electron then I will consider using it. So currently I am leaning towards rewritting what we have in C++ ideally in such a way that is GUI independent.

Do you have any suggestion on how we will document/plan the new project?
The wiki is easy to edit but there are no hooks for notifications.
Perhaps we can use issues for discussion and planning again, then once a conclusion is reached more formal documentation is added to the wiki or the develop branch?

The ideal is to create documentation that can be used for implementation

**Comment by egeldenhuys** [comment]
Actually I am not in favour of using the wiki for the following reasons:
- No hooks, cannot receive telegram notifications.
- No directory structure, page names need to be unique.
- Cannot add files and images using the web interface.
- High maintenance cost, need to manually create a "structure" and keep track of links
- Cannot make reference and discuss.

**Comment by RagingGrim** [comment]
Let's decide on a language first; I feel like that'll dictate our choice for documentation as well.

The only plus I'll give electron is that building doesn't seem too hard.
Then again I haven't really worked with cmake at all so maybe it isn't that bad either.

**Comment by egeldenhuys** [comment]
I succesfully cross compiled a WxWidgets app for Windows from Linux. The static executable was 16 MB.

It was much easier to cross compile, than to compile on Windows itself!

![win](https://imgur.com/gDigbrfl.png)

**Comment by RagingGrim** [comment]
If the cross compilation environment is not too complicated I'd prefer that route!

Last time I needed a reinstall though. I was still naive though 📦

**Comment by egeldenhuys** [comment]
The code for the WxWidgets Hello World has been added to the [prototypes](https://github.com/prothesis-software/prototypes) repo

**Comment by egeldenhuys** [comment]
I assume there is no interest in finishing the nodejs version, so I will be closing those issues and attaching them to the `Finish nodejs-electron version` milestone for future reference.
