### ISSUE TITLE
Base Screen Design and Implementation

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#60]
I have been struggling with how to store documentation alongside the project, such as screen designs, API planning etc. I want to try and use Issues for documentation development. Images uploaded to issues are not part of our repo, yet things are kept together for future reference. The wiki is a pain to manage with images and lacks discussion tools.

If you have suggestions or questions about the screen design, post them here. If you modify a proposed screen design, post a link to the Google Drawing and upload a PNG here for quick reference.

----
### Screen Design
![base screen design - floating centered panel 60](https://user-images.githubusercontent.com/5778739/34079174-bf9fd730-e330-11e7-9a16-0d376fb9f744.png)

[View on Google Drive](https://docs.google.com/drawings/d/1TVPmzg7H1EbF9EYaLi-Mb1jBzUbDYW57JTpONJGpyrs/edit?usp=sharing)

### Layout
![main frame layout 60](https://user-images.githubusercontent.com/5778739/34321404-10a16906-e817-11e7-9fa4-a011faf395ff.png)

[View on Google Drive](https://docs.google.com/drawings/d/13m6jjCXNJUMkonmHijNCU7my7bgg1c38nnYs3LYu5qU/edit?usp=sharing)

----
EDIT 1: Removed original image (No longer the latest). Add latest accepted screen design.
EDIT 2: Add more annotations to screen design. Change title and name.
EDIT 2017-12-27: Update layout doc

**Comment by egeldenhuys** [comment]
Made some changes to the base theme. All other screen designs should inherit from this base.

![prothesis - base screen design](https://user-images.githubusercontent.com/5778739/32994117-a2cad6bc-cd6b-11e7-9e8e-6460b2b2d90a.png)
[View on Google Drive](https://docs.google.com/drawings/d/1TVPmzg7H1EbF9EYaLi-Mb1jBzUbDYW57JTpONJGpyrs/edit?usp=sharing)

**Comment by egeldenhuys** [comment]
[Material Icons](https://material.io/icons/)

**Comment by egeldenhuys** [comment]
Here is a design with a floating centered panel. Similar to many website using Bootstrap:

![base - floating center panel 1](https://user-images.githubusercontent.com/5778739/33003757-6d4f9d2e-cdc5-11e7-9e09-d3571ac67cc5.png)

[View on Google Drive](https://docs.google.com/drawings/d/1TVPmzg7H1EbF9EYaLi-Mb1jBzUbDYW57JTpONJGpyrs/edit?usp=sharing)

**Comment by egeldenhuys** [comment]
Design for Navigation bar:
![navigation bar 1](https://user-images.githubusercontent.com/5778739/33004304-b292a478-cdc8-11e7-8564-eade25f20027.png)

[View on Google Drive](https://docs.google.com/drawings/d/1JisVTwXQ6SpIg927D43b_FAXW6OdVIcgLopMB2Ygtz8/edit?usp=sharing)

**Comment by egeldenhuys** [comment]
The Navigation Bar and Base Screen can be broken into their respective issues for implementation. However everything should be generated based on the GUI config. Only the Base layout such as the title bar and the navigation drawer button will be static.

**Comment by RagingGrim** [comment]
See the wxWidgets [forums ](https://forums.wxwidgets.org/viewtopic.php?t=12857) for a discussion on drawers; Seems like it will be possible.

If no one has gotten around to it yet I'll try to use the builder to implement a drawer and see how it works :)

**Comment by egeldenhuys** [comment]
Managed to get a panel that will stay centered when the window size is changed.

![s1](https://user-images.githubusercontent.com/5778739/33243406-4fba6fcc-d2ee-11e7-85d1-4d491aaa9a94.png)

![s2](https://user-images.githubusercontent.com/5778739/33243404-4f75d150-d2ee-11e7-831c-e2ead49caae0.png)

**Comment by egeldenhuys** [comment]
Reopened due to #85.

New layout design:

![main frame layout 60](https://user-images.githubusercontent.com/5778739/34321404-10a16906-e817-11e7-9fa4-a011faf395ff.png)

[View on Google Drive](https://docs.google.com/drawings/d/13m6jjCXNJUMkonmHijNCU7my7bgg1c38nnYs3LYu5qU/edit?usp=sharing)
