### ISSUE TITLE
Coding Standards

### ISSUE THREAD

**Issue by egeldenhuys** [prothesis-software/prothesis-2#62]
@RagingGrim raised the issue of coding standards. It is important that we follow the same conventions ~or~ and code formatting utility.

**Comment by RagingGrim** [comment]
I'd edit that or to an and :P

**Comment by egeldenhuys** [comment]
I will be following the [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html)

However I will be using the extensions `.cpp` and `.hpp` since my emacs recognises them as c++.

**Comment by egeldenhuys** [comment]
Added by #64
